### ISSUE TITLE
'Accounts' Entity N:N relationship giving Metadata error

### ISSUE THREAD

**Issue by MANEnterprise-Joseph** [keijiinouehotmail/DataverseConnectionViewerPCF#3]
Hello, 

I have created a N:N relationship between the entity 'Accounts' and itself to represent that an account can have many 'Sister Companies'.

The junction table created from this N:N relationship is called cra1c_account_sister_companiesset.

So in config I wrote the following:

{
  "ConfigArray": [
    {
      "ID": "Sales",
      "Description": "This is a configuration for the sales department. Accounts and contacts, as well as opportunities as connection records.",
      "SmallerSizeEnabled": true,
      "DefaultCardsLayoutDescription": "Cards layout for sales department",
      "IsDefault": true,
      "EntitiesForConnectionList": [
        "cra1c_account_sister_companiesset"
      ],
      "RelationshipSchemaNameList": [
        "cra1c_Account_Sister_Companies"
      ]
    }
  ]
}

And now I am getting 
![Capture](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/88129709/30a8d0da-6ace-4c98-802f-1be026badd30)

**Comment by MANEnterprise-Joseph** [comment]
Okay it is no longer giving syntax error, but I still cannot see the connections. Something is wrong with the configuration I suppose. I see the Account I am opening alone without it's 'Sister Companies'.
![Capture](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/88129709/59d90af3-c46b-43a7-9440-e434fbbca8d0)

My configuration is:
![Capture2](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/88129709/20e00623-5805-4724-a083-6f03beb24041)

**Comment by keijiinouehotmail** [comment]
Hello @MANEnterprise-Joseph 

I created new table "Sister Company" ("Sister Companies" in plural).  
I created new N:N relationship between "Account" and "Sister Company".  

By using "Metadata Tools", I found the followings in my environment:  
- The logical name ("LogicalName" on Metadata Tools) of the table "Sister Company" is "keiji_sistercompany"
- The schema name ("SchemaName" on Metadata Tools) of the N:N relationship I created is "keiji_Account_keiji_SisterCompany_keiji_SisterC"

Next, I set the Config Set property of this PCF control as the following:  

```json
{
  "ConfigArray": [
    {
      "ID": "SisterCompany",
      "Description": "Test for Sister Company",
      "SmallerSizeEnabled": true,
      "DefaultCardsLayoutDescription": "Cards layout for Sister Company",
      "IsDefault": true,
      "EntitiesForConnectionList": [
        "keiji_sistercompany"
      ],
      "RelationshipSchemaNameList": [
        "keiji_Account_keiji_SisterCompany_keiji_SisterC"
      ]
    }
  ]
}
```

Lastly, the PCF control worked fine.
![image](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/113506926/e8a5ebeb-5948-4ffe-a5db-52fc59ab442f)

**Comment by MANEnterprise-Joseph** [comment]
Thank you for your reply, I will be testing this on my side. 1 question though, was there a way to do it without creating Sister Company Table? Like the N:N relationship from Account should be also to Account (Account - Account N:N relationship)?

Also, to what values did you set the other properties of this control? EntityID, etc...

**Comment by keijiinouehotmail** [comment]
I'm sorry, I don't understand the intent of your first question.It looks like a question about general table design in Dataverse rather than a question about this PCF control.
In response to your second question, I would like to answer the following:
![image](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/113506926/7cf26993-d0b4-42d6-bfc4-8612f33733ef)
![image](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/113506926/f5b79602-7ddb-41b3-84a3-47ec5119df3e)

I'm working on Account's form, not on Sister Company's from.

**Comment by MANEnterprise-Joseph** [comment]
Thanks again! Regarding the first question, it is not about the general table design. My question was that I want the Account, in this PCF Control, to show other Accounts. I didn't want to create a separate table called Sister Companies.

This is why I created a Many-to-Many relationship between table Accounts and itself:
![Capture](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/88129709/c4ae67c9-580b-4b77-b109-46028cd3e4a2)

**Comment by keijiinouehotmail** [comment]
Now I understood your point. I'll check.

**Comment by keijiinouehotmail** [comment]
Hello @MANEnterprise-Joseph,
I identified the cause of the problem, fixed it, and released a new version.
https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/releases/tag/v1.0.1.8

Note that I leave the EntitiesForConnectionList array empty for Config.

**Comment by MANEnterprise-Joseph** [comment]
I just tried it and it is working perfectly. Thank you for this, nice work!

**Comment by MANEnterprise-Joseph** [comment]
I just tried it and it is working perfectly. Thank you for this, nice work!
