### ISSUE TITLE
Azure OpenAI Endpoint URL Char Limit

### ISSUE THREAD

**Issue by adamhallbeck** [keijiinouehotmail/DataverseConnectionViewerPCF#7]
First, thank you for the effort and time put in to create such a capable PCF control!

When trying to set my Azure OpenAI endpoint URL, I'm getting an error that it cannot exceed 100 characters:

![connectionviewerissue](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/127349964/4802d9a5-1eaf-4dd3-9d1c-b7c9210453ee)

This is after I truncated my deployment name to just two characters. The resource name is thirteen characters long (so I could presumably spin up another, shorter resource and it would be fine) but if this can be extended at all, that would be amazing.

Thanks again.

**Comment by keijiinouehotmail** [comment]
Thank you for your interest in this PCF control.
Please set the value in the classic form editor which does not have char limit as far as my experience.
Click "Switch to classic"
![image](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/113506926/937a1cb7-21f5-4c4c-b313-82fa16f9f1ea)

The classic form editor opens.
![image](https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/assets/113506926/252759a2-1f7e-44e1-9742-da8e7e8f7064)

And then follow the setup instructions.
<https://github.com/keijiinouehotmail/DataverseConnectionViewerPCF/blob/main/Docs/HowToSetUp.md>

**Comment by adamhallbeck** [comment]
I definitely should have tried that. A classic case of user error 🙃 

Thank you!
